/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mp3encoder_Mp3EncoderTest */

#ifndef _Included_com_example_mp3encoder_Mp3EncoderTest
#define _Included_com_example_mp3encoder_Mp3EncoderTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mp3encoder_Mp3EncoderTest
 * Method:    encode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_mp3encoder_Mp3EncoderTest_encode
  (JNIEnv *, jclass);

/*
 * Class:     com_example_mp3encoder_Mp3EncoderTest
 * Method:    init
 * Signature: (Ljava/lang/String;IIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_mp3encoder_Mp3EncoderTest_init
  (JNIEnv *, jclass, jstring, jint, jint, jint, jstring);

/*
 * Class:     com_example_mp3encoder_Mp3EncoderTest
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_mp3encoder_Mp3EncoderTest_destroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
